version: '3.8'

services:
  app:
    build:
      context: .
    container_name: "holo-sounds-app-local"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Taipei
    volumes:
      - tmp_data:/tmp
    ports:
      - "8080:8080"

volumes:
  tmp_data: