version: '3.8'

networks:
  web:
    external: true
    name: traefik_web

services:
  app:
    build:
      context: .
    container_name: "holo-sounds-app"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Taipei
    volumes:
      - tmp_data:/tmp
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.holo-sounds.rule=Host(`holo-sound.harrison-chen.dev`)"
      - "traefik.http.routers.holo-sounds.entrypoints=web"
      - "traefik.http.services.holo-sounds.loadbalancer.server.port=8080"

volumes:
  tmp_data:
